apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: docker.io/tybennett/blog::latest
          ports:
            - name: http
              containerPort: 4000 
          readinessProbe:
            httpGet:
              path: /
              port: 4000 
          resources:
            requests:
              cpu: 500m 
              memory: 256Mi 
            limits:
              memory: 521Mi 
