- Developer:
    - Homelab repo:
        - icon: github.png
          href: https://github.com/ty-bennett
    - Flux docs:
        - icon: flux-cd.png
          href: https://fluxcd.io/flux/
    - Homepage docs:
        - icon: homepage.png
          href: https://gethomepage.dev/
