apiVersion: v1
kind: Service
metadata:
  name: cloudflare-service
  namespace: cloudflare
spec:
  type: ClusterIP  # Can be omitted as it is the default
  selector:
    app: cloudflared  # Routes traffic to Pods with this label
  ports:
    - protocol: TCP
      port: 80        # The service listens here internally
      targetPort: 8080
